import type {
  Appointment,
  Doctor,
  InsurancePlan,
  LabResult,
  Message,
  MessageThread,
  Notification,
  NotificationGroup,
  Patient,
  Prescription,
  SystemMetrics,
  User,
  UserProfile,
} from "@/types";

export const DEMO_USER: User = {
  id: "user-001",
  name: "Sarah Chen",
  email: "sarah.chen@email.com",
  role: "patient",
};

export const PROVIDER_USER: User = {
  id: "user-002",
  name: "Dr. James Wilson",
  email: "j.wilson@healthcare.org",
  role: "provider",
};

export const ADMIN_USER: User = {
  id: "user-003",
  name: "Alex Rivera",
  email: "a.rivera@healthcare.org",
  role: "admin",
};

export const DEFAULT_PROFILES: Record<string, UserProfile> = {
  "user-001": {
    userId: "user-001",
    firstName: "Sarah",
    lastName: "Chen",
    phone: "(555) 234-8891",
    dateOfBirth: "1988-03-15",
    address: { street: "742 Maple Avenue", city: "Portland", state: "OR", zip: "97201" },
    emailNotifications: true,
    smsNotifications: true,
    appointmentReminders: true,
    labResultAlerts: true,
    patient: {
      emergencyContactName: "Michael Chen",
      emergencyContactPhone: "(555) 234-8892",
      bloodType: "O+",
      allergies: "Penicillin",
      preferredPharmacy: "CVS Pharmacy — Downtown Portland",
    },
  },
  "user-002": {
    userId: "user-002",
    firstName: "James",
    lastName: "Wilson",
    phone: "(555) 876-4400",
    dateOfBirth: "1975-11-22",
    address: { street: "1200 Medical Center Dr", city: "Portland", state: "OR", zip: "97205" },
    emailNotifications: true,
    smsNotifications: false,
    appointmentReminders: true,
    labResultAlerts: true,
    provider: {
      specialty: "Internal Medicine",
      licenseNumber: "OR-MD-48291",
      department: "Primary Care",
      bio: "Board-certified internist with 18 years of experience in preventive and chronic care.",
      acceptingNewPatients: true,
    },
  },
  "user-003": {
    userId: "user-003",
    firstName: "Alex",
    lastName: "Rivera",
    phone: "(555) 100-3300",
    dateOfBirth: "1990-07-08",
    address: { street: "500 Admin Plaza", city: "Portland", state: "OR", zip: "97204" },
    emailNotifications: true,
    smsNotifications: false,
    appointmentReminders: false,
    labResultAlerts: true,
    admin: {
      department: "Health IT",
      jobTitle: "Portal Administrator",
    },
  },
};

export function getDefaultProfile(userId: string): UserProfile | null {
  return DEFAULT_PROFILES[userId] ?? null;
}

export const doctors: Doctor[] = [
  {
    id: "doc-001",
    name: "Dr. Emily Hart",
    specialty: "Cardiology",
    rating: 4.9,
    reviewCount: 312,
    nextAvailable: "2026-07-08T09:00:00",
    availability: "today",
    bio: "Board-certified cardiologist specializing in preventive heart care.",
  },
  {
    id: "doc-002",
    name: "Dr. Marcus Lee",
    specialty: "Dermatology",
    rating: 4.7,
    reviewCount: 198,
    nextAvailable: "2026-07-09T14:30:00",
    availability: "soon",
    bio: "Expert in medical and cosmetic dermatology.",
  },
  {
    id: "doc-003",
    name: "Dr. Priya Sharma",
    specialty: "Pediatrics",
    rating: 4.8,
    reviewCount: 421,
    nextAvailable: "2026-07-08T11:00:00",
    availability: "today",
    bio: "Caring pediatrician with 15 years of experience.",
  },
  {
    id: "doc-004",
    name: "Dr. Robert Kim",
    specialty: "Orthopedics",
    rating: 4.6,
    reviewCount: 156,
    nextAvailable: "2026-07-12T10:00:00",
    availability: "soon",
    bio: "Sports medicine and joint replacement specialist.",
  },
  {
    id: "doc-005",
    name: "Dr. Lisa Nguyen",
    specialty: "Neurology",
    rating: 4.9,
    reviewCount: 267,
    nextAvailable: "2026-07-15T08:30:00",
    availability: "unavailable",
    bio: "Neurologist focused on migraines and epilepsy.",
  },
  {
    id: "doc-006",
    name: "Dr. David Okonkwo",
    specialty: "Psychiatry",
    rating: 4.8,
    reviewCount: 189,
    nextAvailable: "2026-07-08T16:00:00",
    availability: "today",
    bio: "Compassionate mental health care provider.",
  },
  {
    id: "doc-007",
    name: "Dr. Anna Kowalski",
    specialty: "Internal Medicine",
    rating: 4.5,
    reviewCount: 534,
    nextAvailable: "2026-07-08T13:00:00",
    availability: "today",
    bio: "Primary care physician for adults of all ages.",
  },
  {
    id: "doc-008",
    name: "Dr. Michael Torres",
    specialty: "Ophthalmology",
    rating: 4.7,
    reviewCount: 143,
    nextAvailable: "2026-07-10T09:30:00",
    availability: "soon",
    bio: "Eye care specialist including LASIK consultations.",
  },
  {
    id: "doc-009",
    name: "Dr. Jennifer Walsh",
    specialty: "ENT",
    rating: 4.6,
    reviewCount: 112,
    nextAvailable: "2026-07-11T15:00:00",
    availability: "soon",
    bio: "Ear, nose, and throat disorders expert.",
  },
  {
    id: "doc-010",
    name: "Dr. Carlos Mendez",
    specialty: "Gastroenterology",
    rating: 4.8,
    reviewCount: 201,
    nextAvailable: "2026-07-14T11:30:00",
    availability: "unavailable",
    bio: "Digestive health and liver disease specialist.",
  },
  {
    id: "doc-011",
    name: "Dr. Rachel Foster",
    specialty: "Oncology",
    rating: 4.9,
    reviewCount: 98,
    nextAvailable: "2026-07-09T10:00:00",
    availability: "soon",
    bio: "Medical oncologist with a patient-centered approach.",
  },
  {
    id: "doc-012",
    name: "Dr. Thomas Berg",
    specialty: "Endocrinology",
    rating: 4.7,
    reviewCount: 176,
    nextAvailable: "2026-07-08T14:00:00",
    availability: "today",
    bio: "Diabetes and thyroid disorder specialist.",
  },
];

export const appointments: Appointment[] = [
  {
    id: "apt-001",
    doctorId: "doc-001",
    doctorName: "Dr. Emily Hart",
    specialty: "Cardiology",
    date: "2026-07-10",
    time: "09:00",
    status: "upcoming",
    location: "Heart Center, Room 204",
  },
  {
    id: "apt-002",
    doctorId: "doc-007",
    doctorName: "Dr. Anna Kowalski",
    specialty: "Internal Medicine",
    date: "2026-07-15",
    time: "10:30",
    status: "upcoming",
    location: "Main Clinic, Room 112",
  },
  {
    id: "apt-003",
    doctorId: "doc-006",
    doctorName: "Dr. David Okonkwo",
    specialty: "Psychiatry",
    date: "2026-07-18",
    time: "14:00",
    status: "upcoming",
    location: "Behavioral Health, Suite 3",
  },
  {
    id: "apt-004",
    doctorId: "doc-012",
    doctorName: "Dr. Thomas Berg",
    specialty: "Endocrinology",
    date: "2026-07-22",
    time: "11:00",
    status: "upcoming",
    location: "Endocrine Clinic, Room 8",
  },
  {
    id: "apt-005",
    doctorId: "doc-002",
    doctorName: "Dr. Marcus Lee",
    specialty: "Dermatology",
    date: "2026-06-20",
    time: "15:30",
    status: "completed",
    location: "Dermatology Wing, Room 5",
  },
  {
    id: "apt-006",
    doctorId: "doc-003",
    doctorName: "Dr. Priya Sharma",
    specialty: "Pediatrics",
    date: "2026-06-05",
    time: "09:00",
    status: "completed",
    location: "Pediatric Center, Room 101",
  },
  {
    id: "apt-007",
    doctorId: "doc-004",
    doctorName: "Dr. Robert Kim",
    specialty: "Orthopedics",
    date: "2026-05-28",
    time: "13:00",
    status: "completed",
    location: "Orthopedic Institute, Room 302",
  },
  {
    id: "apt-008",
    doctorId: "doc-008",
    doctorName: "Dr. Michael Torres",
    specialty: "Ophthalmology",
    date: "2026-05-15",
    time: "10:00",
    status: "completed",
    location: "Eye Center, Room 12",
  },
  {
    id: "apt-009",
    doctorId: "doc-001",
    doctorName: "Dr. Emily Hart",
    specialty: "Cardiology",
    date: "2026-04-22",
    time: "08:30",
    status: "completed",
    location: "Heart Center, Room 204",
  },
  {
    id: "apt-010",
    doctorId: "doc-007",
    doctorName: "Dr. Anna Kowalski",
    specialty: "Internal Medicine",
    date: "2026-03-10",
    time: "11:30",
    status: "completed",
    location: "Main Clinic, Room 112",
  },
  {
    id: "apt-011",
    doctorId: "doc-005",
    doctorName: "Dr. Lisa Nguyen",
    specialty: "Neurology",
    date: "2026-07-25",
    time: "09:30",
    status: "upcoming",
    location: "Neuroscience Center, Room 401",
  },
  {
    id: "apt-012",
    doctorId: "doc-009",
    doctorName: "Dr. Jennifer Walsh",
    specialty: "ENT",
    date: "2026-06-01",
    time: "16:00",
    status: "cancelled",
    location: "ENT Clinic, Room 7",
  },
  {
    id: "apt-013",
    doctorId: "doc-010",
    doctorName: "Dr. Carlos Mendez",
    specialty: "Gastroenterology",
    date: "2026-06-18",
    time: "08:00",
    status: "completed",
    location: "GI Lab, Suite 2",
  },
  {
    id: "apt-014",
    doctorId: "doc-011",
    doctorName: "Dr. Rachel Foster",
    specialty: "Oncology",
    date: "2026-07-30",
    time: "14:30",
    status: "upcoming",
    location: "Cancer Center, Room 15",
  },
  {
    id: "apt-015",
    doctorId: "doc-006",
    doctorName: "Dr. David Okonkwo",
    specialty: "Psychiatry",
    date: "2026-02-14",
    time: "15:00",
    status: "completed",
    location: "Behavioral Health, Suite 3",
  },
  {
    id: "apt-016",
    doctorId: "doc-012",
    doctorName: "Dr. Thomas Berg",
    specialty: "Endocrinology",
    date: "2026-01-20",
    time: "10:00",
    status: "completed",
    location: "Endocrine Clinic, Room 8",
  },
  {
    id: "apt-017",
    doctorId: "doc-002",
    doctorName: "Dr. Marcus Lee",
    specialty: "Dermatology",
    date: "2026-08-05",
    time: "11:30",
    status: "upcoming",
    location: "Dermatology Wing, Room 5",
  },
  {
    id: "apt-018",
    doctorId: "doc-003",
    doctorName: "Dr. Priya Sharma",
    specialty: "Pediatrics",
    date: "2026-04-08",
    time: "14:00",
    status: "cancelled",
    location: "Pediatric Center, Room 101",
  },
  {
    id: "apt-019",
    doctorId: "doc-004",
    doctorName: "Dr. Robert Kim",
    specialty: "Orthopedics",
    date: "2026-08-12",
    time: "09:00",
    status: "upcoming",
    location: "Orthopedic Institute, Room 302",
  },
  {
    id: "apt-020",
    doctorId: "doc-008",
    doctorName: "Dr. Michael Torres",
    specialty: "Ophthalmology",
    date: "2026-07-03",
    time: "13:30",
    status: "completed",
    location: "Eye Center, Room 12",
  },
  {
    id: "apt-021",
    doctorId: "doc-007",
    doctorName: "Dr. Anna Kowalski",
    specialty: "Internal Medicine",
    date: "2026-08-20",
    time: "08:30",
    status: "upcoming",
    location: "Main Clinic, Room 112",
  },
  {
    id: "apt-022",
    doctorId: "doc-001",
    doctorName: "Dr. Emily Hart",
    specialty: "Cardiology",
    date: "2026-06-30",
    time: "16:30",
    status: "cancelled",
    location: "Heart Center, Room 204",
  },
];

export const labResults: LabResult[] = [
  {
    id: "lab-001",
    testName: "Total Cholesterol",
    value: 185,
    unit: "mg/dL",
    referenceMin: 125,
    referenceMax: 200,
    flag: "normal",
    date: "2026-06-28",
    history: [
      { date: "2026-03-15", value: 192 },
      { date: "2025-12-10", value: 198 },
      { date: "2025-09-05", value: 205 },
    ],
  },
  {
    id: "lab-002",
    testName: "LDL Cholesterol",
    value: 118,
    unit: "mg/dL",
    referenceMin: 0,
    referenceMax: 100,
    flag: "borderline",
    date: "2026-06-28",
    history: [
      { date: "2026-03-15", value: 112 },
      { date: "2025-12-10", value: 108 },
      { date: "2025-09-05", value: 115 },
    ],
  },
  {
    id: "lab-003",
    testName: "HDL Cholesterol",
    value: 58,
    unit: "mg/dL",
    referenceMin: 40,
    referenceMax: 60,
    flag: "normal",
    date: "2026-06-28",
    history: [
      { date: "2026-03-15", value: 55 },
      { date: "2025-12-10", value: 52 },
    ],
  },
  {
    id: "lab-004",
    testName: "Triglycerides",
    value: 142,
    unit: "mg/dL",
    referenceMin: 0,
    referenceMax: 150,
    flag: "normal",
    date: "2026-06-28",
    history: [
      { date: "2026-03-15", value: 155 },
      { date: "2025-12-10", value: 148 },
    ],
  },
  {
    id: "lab-005",
    testName: "Fasting Glucose",
    value: 108,
    unit: "mg/dL",
    referenceMin: 70,
    referenceMax: 99,
    flag: "borderline",
    date: "2026-06-28",
    history: [
      { date: "2026-03-15", value: 102 },
      { date: "2025-12-10", value: 98 },
      { date: "2025-09-05", value: 95 },
    ],
  },
  {
    id: "lab-006",
    testName: "HbA1c",
    value: 5.8,
    unit: "%",
    referenceMin: 4.0,
    referenceMax: 5.6,
    flag: "borderline",
    date: "2026-06-28",
    history: [
      { date: "2026-03-15", value: 5.6 },
      { date: "2025-12-10", value: 5.5 },
    ],
  },
  {
    id: "lab-007",
    testName: "Hemoglobin",
    value: 13.8,
    unit: "g/dL",
    referenceMin: 12.0,
    referenceMax: 16.0,
    flag: "normal",
    date: "2026-06-15",
    history: [
      { date: "2026-01-10", value: 13.5 },
      { date: "2025-10-22", value: 13.2 },
    ],
  },
  {
    id: "lab-008",
    testName: "White Blood Cell Count",
    value: 7.2,
    unit: "K/uL",
    referenceMin: 4.5,
    referenceMax: 11.0,
    flag: "normal",
    date: "2026-06-15",
    history: [{ date: "2026-01-10", value: 6.8 }],
  },
  {
    id: "lab-009",
    testName: "Platelet Count",
    value: 245,
    unit: "K/uL",
    referenceMin: 150,
    referenceMax: 400,
    flag: "normal",
    date: "2026-06-15",
    history: [{ date: "2026-01-10", value: 238 }],
  },
  {
    id: "lab-010",
    testName: "Creatinine",
    value: 1.1,
    unit: "mg/dL",
    referenceMin: 0.6,
    referenceMax: 1.2,
    flag: "normal",
    date: "2026-06-15",
    history: [
      { date: "2026-01-10", value: 1.0 },
      { date: "2025-10-22", value: 0.9 },
    ],
  },
  {
    id: "lab-011",
    testName: "TSH",
    value: 4.8,
    unit: "mIU/L",
    referenceMin: 0.4,
    referenceMax: 4.0,
    flag: "borderline",
    date: "2026-05-20",
    history: [
      { date: "2026-02-08", value: 3.9 },
      { date: "2025-11-15", value: 3.2 },
    ],
  },
  {
    id: "lab-012",
    testName: "Vitamin D",
    value: 22,
    unit: "ng/mL",
    referenceMin: 30,
    referenceMax: 100,
    flag: "critical",
    date: "2026-05-20",
    history: [
      { date: "2026-02-08", value: 28 },
      { date: "2025-11-15", value: 32 },
    ],
  },
  {
    id: "lab-013",
    testName: "Potassium",
    value: 5.6,
    unit: "mEq/L",
    referenceMin: 3.5,
    referenceMax: 5.0,
    flag: "critical",
    date: "2026-05-20",
    history: [{ date: "2026-02-08", value: 4.2 }],
  },
  {
    id: "lab-014",
    testName: "ALT",
    value: 32,
    unit: "U/L",
    referenceMin: 7,
    referenceMax: 56,
    flag: "normal",
    date: "2026-05-20",
    history: [{ date: "2026-02-08", value: 28 }],
  },
  {
    id: "lab-015",
    testName: "AST",
    value: 28,
    unit: "U/L",
    referenceMin: 10,
    referenceMax: 40,
    flag: "normal",
    date: "2026-05-20",
    history: [{ date: "2026-02-08", value: 25 }],
  },
  {
    id: "lab-016",
    testName: "BUN",
    value: 22,
    unit: "mg/dL",
    referenceMin: 7,
    referenceMax: 20,
    flag: "borderline",
    date: "2026-04-10",
    history: [{ date: "2026-01-05", value: 18 }],
  },
  {
    id: "lab-017",
    testName: "eGFR",
    value: 72,
    unit: "mL/min",
    referenceMin: 90,
    referenceMax: 120,
    flag: "borderline",
    date: "2026-04-10",
    history: [
      { date: "2026-01-05", value: 78 },
      { date: "2025-09-20", value: 85 },
    ],
  },
];

export const prescriptions: Prescription[] = [
  {
    id: "rx-001",
    name: "Lisinopril",
    dosage: "10mg daily",
    refillsRemaining: 3,
    nextRefillDate: "2026-07-20",
    pharmacy: "CVS Pharmacy - Main St",
  },
  {
    id: "rx-002",
    name: "Atorvastatin",
    dosage: "20mg at bedtime",
    refillsRemaining: 2,
    nextRefillDate: "2026-08-01",
    pharmacy: "CVS Pharmacy - Main St",
  },
  {
    id: "rx-003",
    name: "Metformin",
    dosage: "500mg twice daily",
    refillsRemaining: 5,
    nextRefillDate: "2026-07-15",
    pharmacy: "Walgreens - Oak Ave",
  },
  {
    id: "rx-004",
    name: "Levothyroxine",
    dosage: "50mcg daily",
    refillsRemaining: 1,
    nextRefillDate: "2026-07-10",
    pharmacy: "CVS Pharmacy - Main St",
  },
  {
    id: "rx-005",
    name: "Sertraline",
    dosage: "50mg daily",
    refillsRemaining: 4,
    nextRefillDate: "2026-08-15",
    pharmacy: "Walgreens - Oak Ave",
  },
  {
    id: "rx-006",
    name: "Omeprazole",
    dosage: "20mg before breakfast",
    refillsRemaining: 0,
    nextRefillDate: "2026-07-05",
    pharmacy: "CVS Pharmacy - Main St",
  },
  {
    id: "rx-007",
    name: "Albuterol Inhaler",
    dosage: "2 puffs as needed",
    refillsRemaining: 2,
    nextRefillDate: "2026-09-01",
    pharmacy: "Walgreens - Oak Ave",
  },
  {
    id: "rx-008",
    name: "Vitamin D3",
    dosage: "2000 IU daily",
    refillsRemaining: 6,
    nextRefillDate: "2026-10-01",
    pharmacy: "CVS Pharmacy - Main St",
  },
  {
    id: "rx-009",
    name: "Ibuprofen",
    dosage: "400mg as needed",
    refillsRemaining: 3,
    nextRefillDate: "2026-11-15",
    pharmacy: "Walgreens - Oak Ave",
  },
  {
    id: "rx-010",
    name: "Amlodipine",
    dosage: "5mg daily",
    refillsRemaining: 2,
    nextRefillDate: "2026-07-28",
    pharmacy: "CVS Pharmacy - Main St",
  },
  {
    id: "rx-011",
    name: "Escitalopram",
    dosage: "10mg daily",
    refillsRemaining: 1,
    nextRefillDate: "2026-07-12",
    pharmacy: "Walgreens - Oak Ave",
  },
];

export const messageThreads: MessageThread[] = [
  {
    id: "thread-001",
    participantName: "Dr. Anna Kowalski",
    participantRole: "Internal Medicine",
    lastMessage: "Your lab results look good overall. Let's discuss at your next visit.",
    lastMessageAt: "2026-07-06T14:30:00",
    unread: 1,
  },
  {
    id: "thread-002",
    participantName: "Dr. Emily Hart",
    participantRole: "Cardiology",
    lastMessage: "Please continue your current medication regimen.",
    lastMessageAt: "2026-07-04T10:15:00",
    unread: 0,
  },
  {
    id: "thread-003",
    participantName: "Nurse Patricia Gomez",
    participantRole: "Care Team",
    lastMessage: "Reminder: fasting required for your upcoming blood work.",
    lastMessageAt: "2026-07-02T08:00:00",
    unread: 0,
  },
  {
    id: "thread-004",
    participantName: "Billing Department",
    participantRole: "Administrative",
    lastMessage: "Your insurance claim for the June visit has been processed.",
    lastMessageAt: "2026-06-28T16:45:00",
    unread: 2,
  },
];

export const messages: Message[] = [
  {
    id: "msg-001",
    threadId: "thread-001",
    senderId: "user-001",
    senderName: "Sarah Chen",
    body: "Hi Dr. Kowalski, I received my lab results. Should I be concerned about my glucose levels?",
    sentAt: "2026-07-05T09:00:00",
    readAt: "2026-07-05T11:30:00",
    isPatient: true,
  },
  {
    id: "msg-002",
    threadId: "thread-001",
    senderId: "doc-007",
    senderName: "Dr. Anna Kowalski",
    body: "Hi Sarah, your glucose is slightly elevated but not alarming. We'll monitor it and may adjust your diet plan.",
    sentAt: "2026-07-05T14:00:00",
    readAt: "2026-07-05T16:00:00",
    isPatient: false,
  },
  {
    id: "msg-003",
    threadId: "thread-001",
    senderId: "user-001",
    senderName: "Sarah Chen",
    body: "Thank you! Should I cut back on carbs?",
    sentAt: "2026-07-06T08:30:00",
    readAt: "2026-07-06T12:00:00",
    isPatient: true,
  },
  {
    id: "msg-004",
    threadId: "thread-001",
    senderId: "doc-007",
    senderName: "Dr. Anna Kowalski",
    body: "Your lab results look good overall. Let's discuss at your next visit.",
    sentAt: "2026-07-06T14:30:00",
    isPatient: false,
  },
  {
    id: "msg-005",
    threadId: "thread-002",
    senderId: "doc-001",
    senderName: "Dr. Emily Hart",
    body: "Sarah, your recent ECG shows normal sinus rhythm. No changes needed.",
    sentAt: "2026-07-03T11:00:00",
    readAt: "2026-07-03T12:00:00",
    isPatient: false,
  },
  {
    id: "msg-006",
    threadId: "thread-002",
    senderId: "user-001",
    senderName: "Sarah Chen",
    body: "That's great news. I've been feeling some occasional palpitations though.",
    sentAt: "2026-07-03T15:00:00",
    readAt: "2026-07-04T09:00:00",
    isPatient: true,
  },
  {
    id: "msg-007",
    threadId: "thread-002",
    senderId: "doc-001",
    senderName: "Dr. Emily Hart",
    body: "Please continue your current medication regimen.",
    sentAt: "2026-07-04T10:15:00",
    readAt: "2026-07-04T11:00:00",
    isPatient: false,
  },
  {
    id: "msg-008",
    threadId: "thread-003",
    senderId: "nurse-001",
    senderName: "Nurse Patricia Gomez",
    body: "Hi Sarah, you have lab work scheduled for July 14. Please fast for 12 hours before your appointment.",
    sentAt: "2026-07-01T09:00:00",
    readAt: "2026-07-01T10:00:00",
    isPatient: false,
  },
  {
    id: "msg-009",
    threadId: "thread-003",
    senderId: "user-001",
    senderName: "Sarah Chen",
    body: "Got it, thank you for the reminder!",
    sentAt: "2026-07-01T10:30:00",
    readAt: "2026-07-01T11:00:00",
    isPatient: true,
  },
  {
    id: "msg-010",
    threadId: "thread-003",
    senderId: "nurse-001",
    senderName: "Nurse Patricia Gomez",
    body: "Reminder: fasting required for your upcoming blood work.",
    sentAt: "2026-07-02T08:00:00",
    readAt: "2026-07-02T09:00:00",
    isPatient: false,
  },
  {
    id: "msg-011",
    threadId: "thread-004",
    senderId: "billing-001",
    senderName: "Billing Department",
    body: "We received your insurance information update. Processing may take 3-5 business days.",
    sentAt: "2026-06-25T14:00:00",
    readAt: "2026-06-25T16:00:00",
    isPatient: false,
  },
  {
    id: "msg-012",
    threadId: "thread-004",
    senderId: "user-001",
    senderName: "Sarah Chen",
    body: "Thanks. What was the copay for my last visit?",
    sentAt: "2026-06-27T10:00:00",
    isPatient: true,
  },
  {
    id: "msg-013",
    threadId: "thread-004",
    senderId: "billing-001",
    senderName: "Billing Department",
    body: "Your specialist copay of $40 was applied. A detailed statement is available in your account.",
    sentAt: "2026-06-27T15:00:00",
    isPatient: false,
  },
  {
    id: "msg-014",
    threadId: "thread-004",
    senderId: "billing-001",
    senderName: "Billing Department",
    body: "Your insurance claim for the June visit has been processed.",
    sentAt: "2026-06-28T16:45:00",
    isPatient: false,
  },
];

const allNotifications: Notification[] = [
  {
    id: "notif-001",
    type: "appointment",
    title: "Upcoming Appointment",
    body: "Cardiology visit with Dr. Emily Hart on Jul 10 at 9:00 AM",
    createdAt: "2026-07-06T08:00:00",
    read: false,
    href: "/appointments/apt-001",
  },
  {
    id: "notif-002",
    type: "appointment",
    title: "Appointment Reminder",
    body: "Internal Medicine visit on Jul 15 — add to your calendar",
    createdAt: "2026-07-05T08:00:00",
    read: true,
    href: "/appointments/apt-002",
  },
  {
    id: "notif-003",
    type: "appointment",
    title: "Appointment Confirmed",
    body: "Your psychiatry appointment on Jul 18 has been confirmed",
    createdAt: "2026-07-04T12:00:00",
    read: true,
    href: "/appointments/apt-003",
  },
  {
    id: "notif-004",
    type: "result",
    title: "New Lab Results",
    body: "Your lipid panel results from Jun 28 are now available",
    createdAt: "2026-06-29T09:00:00",
    read: false,
    href: "/lab-results/lab-001",
  },
  {
    id: "notif-005",
    type: "result",
    title: "Critical Result Alert",
    body: "Vitamin D level is critically low — please contact your provider",
    createdAt: "2026-05-21T10:00:00",
    read: false,
    href: "/lab-results/lab-012",
  },
  {
    id: "notif-006",
    type: "result",
    title: "Lab Results Ready",
    body: "Complete blood count results from Jun 15 are available",
    createdAt: "2026-06-16T08:00:00",
    read: true,
    href: "/lab-results/lab-007",
  },
  {
    id: "notif-007",
    type: "prescription",
    title: "Refill Reminder",
    body: "Levothyroxine refill due in 3 days at CVS Pharmacy",
    createdAt: "2026-07-07T07:00:00",
    read: false,
    href: "/prescriptions",
  },
  {
    id: "notif-008",
    type: "prescription",
    title: "Prescription Ready",
    body: "Your Metformin prescription is ready for pickup",
    createdAt: "2026-07-03T14:00:00",
    read: true,
    href: "/prescriptions",
  },
  {
    id: "notif-009",
    type: "prescription",
    title: "Refill Approved",
    body: "Dr. Kowalski approved your Lisinopril refill request",
    createdAt: "2026-06-25T11:00:00",
    read: true,
    href: "/prescriptions",
  },
  {
    id: "notif-010",
    type: "message",
    title: "New Message",
    body: "Dr. Anna Kowalski sent you a message about your lab results",
    createdAt: "2026-07-06T14:30:00",
    read: false,
    href: "/messages/thread-001",
  },
  {
    id: "notif-011",
    type: "message",
    title: "Unread Messages",
    body: "You have 2 unread messages from Billing Department",
    createdAt: "2026-06-28T16:45:00",
    read: false,
    href: "/messages/thread-004",
  },
];

export const notifications = allNotifications;

export const notificationGroups: NotificationGroup[] = [
  {
    type: "appointment",
    label: "Appointments",
    notifications: allNotifications.filter((n) => n.type === "appointment"),
  },
  {
    type: "result",
    label: "Lab Results",
    notifications: allNotifications.filter((n) => n.type === "result"),
  },
  {
    type: "prescription",
    label: "Prescriptions",
    notifications: allNotifications.filter((n) => n.type === "prescription"),
  },
  {
    type: "message",
    label: "Messages",
    notifications: allNotifications.filter((n) => n.type === "message"),
  },
];

export const insurancePlan: InsurancePlan = {
  planName: "BlueCross PPO Gold",
  memberId: "BCX-8847291",
  groupNumber: "GRP-45201",
  deductible: 1500,
  deductibleMet: 875,
  copayPrimary: 25,
  copaySpecialist: 40,
};

export const systemMetrics: SystemMetrics = {
  totalUsers: 12847,
  activePatients: 9342,
  activeProviders: 156,
  appointmentsToday: 342,
  appointmentsThisWeek: 1876,
  labResultsPending: 89,
  messagesUnread: 234,
  systemUptimePercent: 99.97,
  avgResponseTimeMs: 142,
  storageUsedGb: 2.4,
  storageTotalGb: 10,
};

export const patients: Patient[] = [
  {
    id: "pat-001",
    name: "Sarah Chen",
    age: 34,
    mrn: "MRN-100234",
    lastVisit: "2026-06-20",
    conditions: ["Hypertension", "Prediabetes"],
    status: "active",
    nextAppointment: "2026-07-15",
  },
  {
    id: "pat-002",
    name: "Michael Johnson",
    age: 58,
    mrn: "MRN-100235",
    lastVisit: "2026-07-05",
    conditions: ["Type 2 Diabetes", "Hyperlipidemia"],
    status: "active",
    nextAppointment: "2026-07-12",
  },
  {
    id: "pat-003",
    name: "Emily Rodriguez",
    age: 42,
    mrn: "MRN-100236",
    lastVisit: "2026-06-28",
    conditions: ["Asthma", "Seasonal Allergies"],
    status: "active",
    nextAppointment: "2026-07-20",
  },
  {
    id: "pat-004",
    name: "James Williams",
    age: 67,
    mrn: "MRN-100237",
    lastVisit: "2026-07-01",
    conditions: ["Atrial Fibrillation", "CKD Stage 2"],
    status: "active",
    nextAppointment: "2026-07-08",
  },
  {
    id: "pat-005",
    name: "Lisa Thompson",
    age: 29,
    mrn: "MRN-100238",
    lastVisit: "2026-05-15",
    conditions: ["Anxiety", "Migraine"],
    status: "active",
    nextAppointment: "2026-07-18",
  },
  {
    id: "pat-006",
    name: "Robert Davis",
    age: 51,
    mrn: "MRN-100239",
    lastVisit: "2026-04-22",
    conditions: ["GERD", "Obesity"],
    status: "inactive",
  },
  {
    id: "pat-007",
    name: "Jennifer Martinez",
    age: 45,
    mrn: "MRN-100240",
    lastVisit: "2026-07-03",
    conditions: ["Hypothyroidism", "Vitamin D Deficiency"],
    status: "active",
    nextAppointment: "2026-07-22",
  },
  {
    id: "pat-008",
    name: "David Anderson",
    age: 73,
    mrn: "MRN-100241",
    lastVisit: "2026-06-10",
    conditions: ["COPD", "Hypertension", "Osteoarthritis"],
    status: "active",
    nextAppointment: "2026-07-11",
  },
  {
    id: "pat-009",
    name: "Amanda Taylor",
    age: 36,
    mrn: "MRN-100242",
    lastVisit: "2026-03-08",
    conditions: ["PCOS"],
    status: "inactive",
  },
  {
    id: "pat-010",
    name: "Christopher Brown",
    age: 48,
    mrn: "MRN-100243",
    lastVisit: "2026-07-06",
    conditions: ["Sleep Apnea", "Hypertension"],
    status: "active",
    nextAppointment: "2026-07-25",
  },
  {
    id: "pat-011",
    name: "Maria Garcia",
    age: 55,
    mrn: "MRN-100244",
    lastVisit: "2026-06-18",
    conditions: ["Rheumatoid Arthritis"],
    status: "active",
    nextAppointment: "2026-08-01",
  },
  {
    id: "pat-012",
    name: "Kevin Lee",
    age: 31,
    mrn: "MRN-100245",
    lastVisit: "2026-05-30",
    conditions: ["Eczema"],
    status: "active",
    nextAppointment: "2026-07-09",
  },
];

export function getDoctorById(id: string): Doctor | undefined {
  return doctors.find((d) => d.id === id);
}

export function getMessagesByThread(threadId: string): Message[] {
  return messages.filter((m) => m.threadId === threadId);
}

export function getUnreadNotificationCount(): number {
  return notifications.filter((n) => !n.read).length;
}

